services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: robogo
      POSTGRES_PASSWORD: robogo_pass
      POSTGRES_DB: robogo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      dockerfile: server/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8081"
    depends_on:
      - db
  gateway:
    build:
      dockerfile: api-gateway/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - server
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://api-gateway:8080
    ports:
      - "80:80"
  genai:
    build:
      context: ./genai
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

volumes:
  postgres_data:
