services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: robogo
      POSTGRES_PASSWORD: robogo_pass
      POSTGRES_DB: robogo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      dockerfile: server/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/robogo_db
      SPRING_DATASOURCE_USERNAME: robogo
      SPRING_DATASOURCE_PASSWORD: robogo_pass
  gateway:
    build:
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server

volumes:
  postgres_data:
