server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: server_route
          uri: http://server:8081
          predicates:
            - Path=/api/server/**
          filters:
            - StripPrefix=1
  web:
    resources:
      static-locations: []

logging:
  level:
    root: DEBUG