server:
  port: 8080

spring:
  application:
    name: api-gateway

gateway:
  routes:
    - id: server_route
      uri: http://localhost:8081
      predicates:
        - Path=/api/server/**
      filters:
        - StripPrefix=1
