server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: http://server:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: server_route
          uri: http://server:8081
          predicates:
            - Path=/api/server/**
          filters:
            - StripPrefix=1
        - id: genai_route
          uri: http://genai:5000
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

  web:
    resources:
      static-locations: []
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    org.springframework.security: INFO
    reactor.netty: INFO 