server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: server_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/server/**
          filters:
            - StripPrefix=1
        - id: genai_route
          uri: http://localhost:5000
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=1

  web:
    resources:
      static-locations: []
  security:
    cors:
      allowed-origins:
        - ${FRONTEND_ORIGIN:http://localhost:3000}

logging:
  level:
    root: DEBUG 