apiVersion: v2
name: robogo
description: Robogo all-in-one deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: 18.3.2
    repository: https://charts.bitnami.com/bitnami