namespace:
  name: team-robogo
  create: false

configMap:
  name: screen-config

database:
  service:
    name: db-service
    port: 5432

gateway:
  service:
    name: gateway-service
    port: 8080
  replicaCount: 1

client:
  service:
    name: client-service
    port: 80
    nodePort: 30000

server:
  service:
    name: server-service
    port: 8081
    nodePort: 30001
  replicaCount: 1

# Monitoring components
kube-prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false

loki:
  enabled: true
  # Promtail is the agent that ships logs to Loki.
  promtail:
    enabled: true
  grafana:
    enabled: false # We use the Grafana from kube-prometheus-stack
