namespace: team-robogo

db:
  name: robogo_db
  user: robogo
  host: db-service
  password: robogo_pass
  port: 5432

gateway:
  image: ghcr.io/aet-devops25/team-robogo/api-gateway:main
  port: 8080
  serverHost: server-service
  genaiHost: genai-service

server:
  image: ghcr.io/aet-devops25/team-robogo/server:main
  port: 8081

client:
  image: ghcr.io/aet-devops25/team-robogo/client:main
  apiGatewayHost: gateway-service
  port: 80
  nodePort: 30000

genai:
  image: ghcr.io/aet-devops25/team-robogo/genai:main
  port: 8000
  chairApiKey: "sk-xxx"
  openaiApiKey: "sk-yyy"