apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: screen
spec:
  selector:
    app: server
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
      protocol: TCP
  type: NodePort
