{
 "title": "Spring Boot 2.1 Statistics",
 "tags": [
  "spring-boot",
  "micrometer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(up{job=~\"^.*spring-boot.*$\"}, application)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP",
    "query": "label_values(hikaricp_connections_max{application=\"$application\"}, pool)"
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Info",
   "type": "singlestat",
   "description": "Information about the Spring Boot Application",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spring_build_info{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "The system CPU usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "The uptime of the application",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "The start time of the application",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "time:YYYY-MM-DD HH:mm:ss",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "description": "The number of open file descriptors",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "The memory used in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{area}}-{{id}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "The number of threads",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "graph",
   "description": "The number of classes loaded",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "jvm_classes_unloaded_classes_total{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "graph",
   "description": "The time spent in garbage collection",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}}, {{cause}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "The number of http requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  { "title": "HikariCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Connections max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_max{application=\"$application\", instance=\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_min{application=\"$application\", instance=\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  { "title": "Logback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Log Events",
   "type": "graph",
   "description": "The number of log events",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}