---
- name: Deploy Robogo Application
  hosts: "{{ target_hosts | default('localhost') }}"
  connection: "{{ connection_type | default('local') }}"
  vars:
    env: "{{ environment | default('local') }}"
  tasks:
    - name: Check if kubectl is installed
      command: kubectl version --client
      register: kubectl_check
      ignore_errors: yes

    - name: Install kubectl if not present
      when: kubectl_check.rc != 0
      block:
        - name: Install kubectl (Windows)
          win_chocolatey:
            name: kubernetes-cli
            state: present
          when: ansible_os_family == "Windows"

        - name: Install kubectl (Linux)
          apt:
            name: kubectl
            state: present
            update_cache: yes
          when: ansible_os_family == "Debian"

    - name: Apply Terraform configuration
      shell: |
        cd {{ playbook_dir }}/../terraform
        terraform init
        terraform apply -var-file=terraform.tfvars.{{ env }} -auto-approve
      args:
        creates: "{{ playbook_dir }}/../terraform/.terraform.lock.hcl"

    - name: Apply Kubernetes manifests with environment variables
      shell: |
        set -a
        source {{ playbook_dir }}/../kubernetes/env.{{ env }}
        set +a
        envsubst < {{ playbook_dir }}/../kubernetes/deployment.yaml | kubectl apply -f -
      register: k8s_apply
      changed_when: "'unchanged' not in k8s_apply.stdout"

    - name: Wait for deployment to be ready
      shell: |
        kubectl rollout status deployment/robogo-server -n team-robogo
      register: rollout_status
      until: rollout_status.rc == 0
      retries: 30
      delay: 10 