apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: screen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/aet-devops25/team-robogo/server:main # Deploy the version pushed to main branch, not wip PR branches
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db-service:5432/robogo_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "robogo"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "robogo_pass"

