global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.team-robogo.svc:9090']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['gateway-service.team-robogo.svc:8080']

  - job_name: 'server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['server-service.team-robogo.svc:8081']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter.team-robogo.svc:9187']

  - job_name: 'genai'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai-service.team-robogo.svc:8000'] 