apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: screen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ghcr.io/aet-devops25/team-robogo/api-gateway:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
