apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.project.name }}-alertmanager-config
  labels:
    app: {{ .Values.project.name }}-alertmanager
    component: monitoring
data:
  alertmanager.yml: |
{{ .Values.alertmanager.config | toYaml | indent 4 }} 