apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.project.name }}-alertmanager
  labels:
    app: {{ .Values.project.name }}-alertmanager
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.project.name }}-alertmanager
  template:
    metadata:
      labels:
        app: {{ .Values.project.name }}-alertmanager
        component: monitoring
    spec:
      containers:
      - name: alertmanager
        image: {{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}
        ports:
        - containerPort: {{ .Values.alertmanager.service.port }}
        args:
        - '--config.file=/etc/alertmanager/alertmanager.yml'
        - '--storage.path=/alertmanager'
        - '--web.listen-address=:{{ .Values.alertmanager.service.port }}'
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        - name: alertmanager-storage
          mountPath: /alertmanager
        resources:
          {{- toYaml .Values.alertmanager.resources | nindent 10 }}
      volumes:
      - name: alertmanager-config
        configMap:
          name: {{ .Values.project.name }}-alertmanager-config
      - name: alertmanager-storage
        {{- if .Values.alertmanager.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.project.name }}-alertmanager-pvc
        {{- else }}
        emptyDir: {}
        {{- end }} 