apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.targetPort }}
      nodePort: {{ .Values.client.nodePort }}
  selector:
    app: client