apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: team-robogo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ghcr.io/aet-devops25/team-robogo/client:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
