apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: {{ .Values.client.image }}
          ports:
            - containerPort: {{ .Values.client.targetPort }}
          env:
            - name: GATEWAY_HOST
              value: {{ .Values.client.apiGatewayHost }}
            {{- if .Values.client.env }}
            {{- range $key, $value := .Values.client.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}