apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: team-robogo
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
