apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  ports:
    - port: {{ .Values.genai.port }}
      targetPort: {{ .Values.genai.port }}
  selector:
    app: genai
  type: ClusterIP