apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: config
data:
  dashboard-provider.yml: |-
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/provisioning/dashboards
  postgres-dashboard.json: |-
    {{ .Files.Get "files/monitoring/grafana/dashboards/postgres-dashboard.json" | nindent 4 }}
  spring-boot-dashboard.json: |-
    {{ .Files.Get "files/monitoring/grafana/dashboards/spring-boot-dashboard.json" | nindent 4 }}


