{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.project.name }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
        - "grafana.{{ .Values.ingress.host }}"
        - "alertmanager.{{ .Values.ingress.host }}"
      secretName: "{{ .Values.ingress.secretName }}"
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.port }}
    - host: "grafana.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: {{ .Values.grafana.service.port }}
    - host: "alertmanager.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.project.name }}-alertmanager-service
                port:
                  number: {{ .Values.alertmanager.service.port }}
{{- end }}
