apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}?sslmode=disable"