apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-exporter
spec:
  ports:
    - port: {{ .Values.postgresExporter.port | default 9187 }}
      targetPort: {{ .Values.postgresExporter.port | default 9187 }}
      protocol: TCP
      name: http
  selector:
    app: postgres-exporter