apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: {{ .Release.Namespace }}
data:
  alert.rules.yml: |-
{{ .Files.Get "files/monitoring/alert.rules.yml" | indent 4 }} 