apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
  selector:
    app: server
  type: ClusterIP