apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      initContainers:
        - name: init-slides-dir
          image: busybox:1.35
          command: ['sh', '-c', 'mkdir -p {{ .Values.server.slides.path }} && chmod 755 {{ .Values.server.slides.path }}']
          volumeMounts:
            - name: slides-volume
              mountPath: {{ .Values.server.slides.path }}
      containers:
        - name: server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.user | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: SPRING_REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: SPRING_REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: SPRING_REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
            - name: ADMIN_USERNAME
              value: {{ .Values.server.adminUsername }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.server.adminPassword }}
            - name: ADMIN_EMAIL
              value: {{ .Values.server.adminEmail }}
            - name: SLIDES_PATH
              value: {{ .Values.server.slides.path }}
          volumeMounts:
            - name: slides-volume
              mountPath: {{ .Values.server.slides.path }}
      volumes:
        - name: slides-volume
          emptyDir: {}