apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slides-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.slides.persistence.size }}
{{- if .Values.server.slides.persistence.storageClassName }}
  storageClassName: {{ .Values.server.slides.persistence.storageClassName }}
{{- end }} 