apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: screen
spec:
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
  type: NodePort
