apiVersion: apps/v1
kind: Deployment
metadata:
  name: robogo-server
  namespace: ${NAMESPACE}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: robogo-server
  template:
    metadata:
      labels:
        app: robogo-server
    spec:
      containers:
      - name: server
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: ${CONTAINER_PORT}
        envFrom:
        - configMapRef:
            name: robogo-config-${ENVIRONMENT}
        resources:
          requests:
            memory: "${MEMORY_REQUEST}"
            cpu: "${CPU_REQUEST}"
          limits:
            memory: "${MEMORY_LIMIT}"
            cpu: "${CPU_LIMIT}"
---
apiVersion: v1
kind: Service
metadata:
  name: robogo-server
  namespace: ${NAMESPACE}
spec:
  selector:
    app: robogo-server
  ports:
  - port: ${SERVICE_PORT}
    targetPort: ${CONTAINER_PORT}
  type: ${SERVICE_TYPE} 