---
- name: Setup Kubernetes (k3s) on EC2
  hosts: ec2
  become: true

  tasks:
    - name: Install required packages
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Wait for kubeconfig to be ready
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        timeout: 30

    - name: Copy kubeconfig to user manually
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
        chown -R ubuntu:ubuntu /home/ubuntu/.kube
        sed -i "s/127.0.0.1/localhost/" /home/ubuntu/.kube/config
      become: true

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
