---
- name: Setup Kubernetes (k3s) on EC2
  hosts: ec2
  become: true

  tasks:
    - name: Install required packages
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Wait for kubeconfig to be ready
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        timeout: 30

    - name: Copy kubeconfig to regular user
      become_user: ec2-user
      shell: |
        mkdir -p /home/ec2-user/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/ec2-user/.kube/config
        chown ec2-user:ec2-user /home/ec2-user/.kube/config
        sed -i "s/127.0.0.1/localhost/" /home/ec2-user/.kube/config

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
