---
- name: Setup Kubernetes (k3s) on EC2
  hosts: ec2
  become: true

  tasks:
    #- name: Install required packages
    #  apt:
    #    name: curl
    #    state: present
    #    update_cache: yes
    #  become: true

    - name: Install k3s if not already installed
      shell: |
        if ! command -v k3s >/dev/null 2>&1; then
          curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san {{ ansible_host }} --node-external-ip {{ ansible_host }} --write-kubeconfig-mode 644" sh -
        else
          echo "k3s already installed"
        fi
      become: true


    - name: Wait for kubeconfig to be ready
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        timeout: 30

    - name: Copy kubeconfig to user manually
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
        chown -R ubuntu:ubuntu /home/ubuntu/.kube
        sed -i "s/127.0.0.1/localhost/" /home/ubuntu/.kube/config
      become: true

    - name: Install Helm if not already installed
      shell: |
        if ! command -v helm >/dev/null 2>&1; then
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        else
          echo "Helm is already installed"
        fi
      args:
        executable: /bin/bash
