name: AWS Deployment

# For testing purposes I want this to be inputed manually right now.
# When everything is working, I will change this to secrets.
on:
  workflow_dispatch:
    inputs:
      PRIVATE_KEY:
        description: 'aws ssh key in a pem file'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write ssh key to infra/pk.pem
        run: |
          echo "${{ github.event.inputs.PRIVATE_KEY }}" > infra/terra/pk.pem

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Create EC2
        run: |
          cd infra/terra
          chmod 400 pk.pem
          ssh -i pk.pem admin@$(shell terraform output -raw ip)
          terraform init -input=false
          terraform apply -input=false --auto-approve
