name: CI Pipeline

on:
  push: # Trigger all pushes
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  release:
    types: [created, published]

jobs:
  server:
    name: Build Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tag (replace / with -)
        id: server_tag
        run: |
          SAFE_TAG=$(echo "${{ github.ref_name }}" | tr '/' '-')
          echo "tag=$SAFE_TAG" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/aet-devops25/team-robogo/server:latest
            ghcr.io/aet-devops25/team-robogo/server:${{ github.sha }}
            ghcr.io/aet-devops25/team-robogo/server:${{ steps.server_tag.outputs.tag }}

  client:
    name: Build Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tag (replace / with -)
        id: client_tag
        run: |
          SAFE_TAG=$(echo "${{ github.ref_name }}" | tr '/' '-')
          echo "tag=$SAFE_TAG" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/aet-devops25/team-robogo/client:latest
            ghcr.io/aet-devops25/team-robogo/client:${{ github.sha }}
            ghcr.io/aet-devops25/team-robogo/client:${{ steps.client_tag.outputs.tag }}

  api-gateway:
    name: Build API Gateway
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tag (replace / with -)
        id: gateway_tag
        run: |
          SAFE_TAG=$(echo "${{ github.ref_name }}" | tr '/' '-')
          echo "tag=$SAFE_TAG" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API Gateway Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./api-gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/aet-devops25/team-robogo/api-gateway:latest
            ghcr.io/aet-devops25/team-robogo/api-gateway:${{ github.sha }}
            ghcr.io/aet-devops25/team-robogo/api-gateway:${{ steps.gateway_tag.outputs.tag }}
  genai:
    name: Build GenAI Service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tag (replace / with -)
        id: genai_tag
        run: |
          SAFE_TAG=$(echo "${{ github.ref_name }}" | tr '/' '-')
          echo "tag=$SAFE_TAG" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push GenAI Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./genai
          file: ./genai/Dockerfile
          push: true
          tags: |
            ghcr.io/aet-devops25/team-robogo/genai:latest
            ghcr.io/aet-devops25/team-robogo/genai:${{ github.sha }}
            ghcr.io/aet-devops25/team-robogo/genai:${{ steps.genai_tag.outputs.tag }}