name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feat/**'  # matches all feature branches
      - 'develop'
  pull_request:
    branches:
      - main
      - 'feat/**'  # matches all feature branches
      - 'develop'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  release:
    types: [ created, published ]

jobs:
  server:
    name: Build Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/aet-devops25/team-robogo/server:latest
            ghcr.io/aet-devops25/team-robogo/server:${{ github.sha }}

  client:
    name: Build Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/aet-devops25/team-robogo/client:latest
            ghcr.io/aet-devops25/team-robogo/client:${{ github.sha }}

  api-gateway:
    name: Build API Gateway
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API Gateway Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./api-gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/aet-devops25/team-robogo/api-gateway:latest
            ghcr.io/aet-devops25/team-robogo/api-gateway:${{ github.sha }}

