name: Rancher Deployment

on:
  workflow_dispatch:
    inputs:
      RANCHER_TOKEN:
        description: 'Rancher API Token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.11.0'

      - name: Write Kubeconfig file
        run: |
          cat > .kubeconfig <<EOF
          apiVersion: v1
          kind: Config
          clusters:
          - name: "student"
            cluster:
              server: "https://rancher.ase.cit.tum.de/k8s/clusters/c-m-nhcfjg9h"

          users:
          - name: "student"
            user:
              token: "${{ github.event.inputs.RANCHER_TOKEN }}"

          contexts:
          - name: "student"
            context:
              user: "student"
              cluster: "student"

          current-context: "student"
          EOF
          chmod 600 .kubeconfig

      - name: Helm Deployment
        env:
          KUBECONFIG: ${{ github.workspace }}/.kubeconfig
        run: |
          cd ./infra/helm/screen
          helm dependency build
          kubectl label namespace team-robogo app.kubernetes.io/managed-by=Helm --overwrite || true
          kubectl annotate namespace team-robogo meta.helm.sh/release-name=screen --overwrite || true
          kubectl annotate namespace team-robogo meta.helm.sh/release-namespace=team-robogo --overwrite || true
          helm upgrade --install screen . --namespace team-robogo --skip-crds
